const ADMIN = "ADMIN";
const PROJECT_COORDINATOR = "PROJECT_COORDINATOR";
const CLIENT = "CLIENT";
const CLIENT_VENDOR = "CLIENT_VENDOR";

module.exports = {
  ADMIN,
  PROJECT_COORDINATOR,
  CLIENT,
  CLIENT_VENDOR,
};
